# Web Scraping

<img src="cat-scraping.png" width="250" height="250">

#### Acknowledgement:
This file was initially conceived and created by my former student, Jeremy Liu.

In [1]:
# pip install requests
# pip install pandas
# pip install beautifulsoup4

In [2]:
# Import necessary libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
# Set the url
url = "https://phoenix.craigslist.org/"

<img src="./craigslist-snapshot.png">

In [4]:
# Get Url
page = requests.get(url)

In [5]:
# View Content
page.content
#type(page)

b'<!DOCTYPE html>\n<html class="no-js">\n<head>\n\n\t<meta charset="UTF-8">\n\t<meta http-equiv="X-UA-Compatible" content="IE=Edge">\n\t<meta name="viewport" content="width=device-width,initial-scale=1">\n\t<meta property="og:site_name" content="craigslist">\n\t<meta name="twitter:card" content="preview">\n\t<meta property="og:url" content="https://phoenix.craigslist.org/">\n\t<link rel="canonical" href="https://phoenix.craigslist.org/">\n\n<title>craigslist: phoenix, AZ jobs, apartments, for sale, services, community, and events</title>\n<meta name="description" content="craigslist provides local classifieds and forums for jobs, housing, for sale, services, local community, and events">\n<meta name="google-site-verification" content="Ie0Do80edB2EurJYj-bxqMdX7zkMjx_FnjtQp_XMFio">\n<meta name="msvalidate.01" content="3402AB8563AB1E080501C21306FE7811" />\n<meta name="ICBM" content="33.448299, -112.072998">\n<link type="text/css" rel="stylesheet" media="all" href="//www.craigslist.org/styles/cl.css?v=5826de27c327d61d2169c6a45af814f9">\n<link type="text/css" rel="stylesheet" media="all" href="//www.craigslist.org/styles/homepage.css?v=4391172eeea9c8621386a90e30f057c1">\n<link type="text/css" rel="stylesheet" media="all" href="//www.craigslist.org/styles/jquery-ui-clcustom.css?v=3b05ddffb7c7f5b62066deff2dda9339">\n<link rel="prefetch" href="//www.craigslist.org/js/search-concat.min.js?v=b3fa2bc3c80149a1d5dfd557bfb24946">\n</head>\n<body class="homepage en">\n<script type="text/javascript"><!--\n    function C(k){return(document.cookie.match(\'(^|; )\'+k+\'=([^;]*)\')||0)[2]}\n    var pagetype, pagemode;\n    (function(){\n        var h = document.documentElement;\n        h.className = h.className.replace(\'no-js\', \'js\');\n        var b = document.body;\n        var bodyClassList = b.className.split(/\\s+/);;\n        pagetype = bodyClassList[0]; // dangerous assumption\n        var fmt = C(\'cl_fmt\');\n        if ( fmt === \'regular\' || fmt === \'mobile\' ) {\n            pagemode = fmt;\n        } else if (screen.width <= 480) {\n            pagemode = \'mobile\';\n        } else {\n            pagemode = \'regular\';\n        }\n        pagemode = pagemode === \'mobile\' ? \'mobile\' : \'desktop\';\n        bodyClassList.push(pagemode);\n        if (C(\'hidesearch\') === \'1\' && pagemode !== \'mobile\') {\n            bodyClassList.push(\'hide-search\');\n        }\n        var width = window.innerWidth || document.documentElement.clientWidth;\n        if (width > 1000) { bodyClassList.push(\'w1024\'); }\n        if (typeof window.sectionBase !== \'undefined\') {\n            var mode = (decodeURIComponent(C(\'cl_tocmode\') || \'\').match(new RegExp(window.sectionBase + \':([^,]+)\', \'i\')) || {})[1] || window.defaultView;\n            if (mode) {\n                bodyClassList.push(mode);\n            }\n        }\n        b.className = bodyClassList.join(\' \');\n    }());\n--></script>\n\n\n<div class="wrapper">\n    <section class="page-container">\n        <div class="bglogo"></div>\n        <div class="tryapp">\n    try the craigslist app &raquo;\n    <a class="appstorebtn"\n    href="https://play.google.com/store/apps/details?id=org.craigslist.CraigslistMobile">\n        Android\n    </a>\n    <a class="appstorebtn"\n    href="https://apps.apple.com/us/app/craigslist/id1336642410">\n        iOS\n    </a>\n</div>\n<header class="global-header wide">\n   <a class="header-logo" name="logoLink" href="/">CL</a>\n\n    <nav class="breadcrumbs-container">\n\n<ul class="breadcrumbs">\n        <li class="crumb area">\n            <p>\n                    <a href="/">phoenix</a>\n\n            </p>\n        </li>\n\n\n\n\n</ul>\n    </nav>\n\n<div class="userlinks">\n    <ul class="user-actions">\n        <li class="user post">\n            <a href="https://post.craigslist.org/c/phx">post</a>\n        </li>\n        <li class="user account">\n            <a href="https://accounts.craigslist.org/login/home">account</a>\n        </li>\n    </ul>\n    <ul class="user-favs-discards">\n        <li class="user">\n            <div class="favorites">\n                <a href="#" class="favlink"><span class="icon icon-star fav" aria-hidden="true"></span><span class="fav-number"></span><span class="fav-label"> favorites</span></a>\n            </div>\n        </li>\n        <li class="user discards">\n          <form class="unfavform js-only" method="POST" action="/favorites">\n            <div class="to-banish-page">\n              <input type="hidden" class="lastLink" name="lastLink" value="">\n              <input type="hidden" class="lastTitle" name="lastTitle" value="">\n              <input type="hidden" class="unfaves" name="fl">\n              <input type="hidden" name="uf" value="1">\n              <a href="#" class="to-banish-page-link">\n                <span class="icon icon-trash red" aria-hidden="true"></span>\n                <span class="banished_count"></span>\n                <span class="discards-label"> hidden</span>\n              </a>\n            </div>\n          </form>\n        </li>\n    </ul>\n</div>\n\n</header>\n<header class="global-header narrow">\n   <a class="header-logo" href="/">CL</a>\n    <nav class="breadcrumbs-container">\n\n<ul class="breadcrumbs">\n\n\nphoenix\n\n\n</ul>\n\n\n    </nav>\n    <span class="linklike show-wide-header">...</span>\n</header>\n\n        <nav id="topban" class="regular">\n            <div class="regular-area">\n                <h2 class="area">phoenix, AZ</h2>\n                <ul class="sublinks"><li><a href="/cph/" title="central/south phx">cph</a></li><li><a href="/evl/" title="east valley">evl</a></li><li><a href="/nph/" title="phx north">nph</a></li><li><a href="/wvl/" title="west valley">wvl</a></li></ul>\n            </div>\n            <div class="enter-area">\n                <input type="text" class="subarea-input flatinput"\n                    data-autocomplete="subarea" value="">\n            </div>\n            <div class="custom-area no-name">\n                <h2 class="area"></h2>\n                <div class="radius-info">\n                    within <span class="distance"></span> mi of <span class="postal"></span>\n                </div>\n                <div class="exit-subarea">&times;</div>\n            </div>\n        </nav>\n       <div id="leftbar">\n            <div id="logo">\n    <a href="https://www.craigslist.org/about/sites">craigslist</a>\n</div>\n\n<ul id="postlks">\n    <li><a id="post" href="https://post.craigslist.org/c/phx">create a posting</a></li>\n    <li><a href="https://accounts.craigslist.org/login/home">my account</a></li>\n</ul>\n\n<form id="search" class="homepage-search" action="/search/" method="GET">\n    <input type="hidden" name="sort" value="rel">\n    <input type="hidden" name="ordinal" id="ordinal" value="1">\n    <input type="hidden" name="ratio" id="ratio" value="0">\n    <input type="hidden" name="clicked" id="clicked" value="0">\n    <input id="query" class="querybox flatinput" name="query" data-autocomplete="search-count" autocorrect="off" autocapitalize="off" placeholder="search craigslist" autofocus="autofocus">\n    <select id="catAbb" name="catAbb" class="homepage-category-picker">\n        <option value="" selected="selected">select category</option>\n        <option value="ccc">community</option>\n        <option value="eee">events</option>\n        <option value="ggg">gigs</option>\n        <option value="hhh">housing</option>\n        <option value="jjj">jobs</option>\n        <option value="rrr">resumes</option>\n        <option value="sss">for sale</option>\n        <option value="bbb">services</option>\n    </select>\n    <button type="submit" id="go" class="searchbtn"><span class="icon icon-search"><span class="screen-reader-text">search craigslist</span></span></button>\n</form>\n\n<h4 id="calban"><a href="/d/events-classes/search/eee">event calendar</a></h4>\n<table class="cal">\n    <tr class="days">\n            <th>M</th>\n            <th>T</th>\n            <th>W</th>\n            <th>T</th>\n            <th>F</th>\n            <th>S</th>\n            <th>S</th>\n    </tr>\n        <tr>\n                <td class="">6</td>\n                <td class="today "><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-07">7</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-08">8</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-09">9</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-10">10</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-11">11</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-12">12</a></td>\n        </tr>\n        <tr>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-13">13</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-14">14</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-15">15</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-16">16</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-17">17</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-18">18</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-19">19</a></td>\n        </tr>\n        <tr>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-20">20</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-21">21</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-22">22</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-23">23</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-24">24</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-25">25</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-26">26</a></td>\n        </tr>\n        <tr>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-27">27</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-28">28</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-29">29</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-30">30</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-31">31</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-08-01">1</a></td>\n                <td class=""><a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-08-02">2</a></td>\n        </tr>\n</table>\n\n\n<ul class="leftlinks" id="user_resources">\n    \n    \n        <li><a href="https://www.craigslist.org/about/craigslist_app">craigslist app<sup class="neu">new</sup></a></li>\n    <li><a href="https://www.craigslist.org/about/help/">help, faq, abuse, legal</a></li>\n    <li><a href="https://www.craigslist.org/about/scams">avoid scams &amp; fraud</a></li>\n    <li><a href="https://www.craigslist.org/about/safety">personal safety tips</a></li>\n    <li><a href="//www.craigslist.org/about/terms.of.use.en-us">terms of use<sup class="neu">new</sup></a></li>\n    <li><a href="https://www.craigslist.org/about/privacy.policy">privacy policy</a></li>\n    <li><a href="https://www.craigslist.org/about/help/system-status">system status</a></li>\n</ul>\n\n<ul class="leftlinks" id="about_craigslist">\n    <li><a href="https://www.craigslist.org/about/">about craigslist</a></li>\n    <li><a href="https://www.craigslist.org/about/open_source">craigslist open source</a></li>\n    <li><a href="http://blog.craigslist.org/">craigslist blog</a></li>\n    <li><a href="https://www.craigslist.org/about/best/all/">best-of-craigslist</a></li>\n\n    <li><a href="http://www.craigslistjoe.com/">"craigslist joe"</a></li>\n    <li><a href="https://craignewmarkphilanthropies.org/">craig newmark<br>philanthropies</a></li>\n</ul>\n\n\n        </div>\n        <div id="center">\n            <div class="community">\n                \n        <div id="ccc" class="col">\n        <h4 class="ban"><a href="/d/community/search/ccc" class="ccc" data-alltitle="all community" data-cat="ccc"><span class="txt">community<sup class="c"></sup></span></a></h4>\n        <div class="cats">\n        <ul id="ccc0" class="left">\n<li><a href="/d/activity-partners/search/act" class="act" data-cat="act"><span class="txt">activities<sup class="c"></sup></span></a></li>\n<li><a href="/d/artists/search/ats" class="ats" data-cat="ats"><span class="txt">artists<sup class="c"></sup></span></a></li>\n<li><a href="/d/childcare/search/kid" class="kid" data-cat="kid"><span class="txt">childcare<sup class="c"></sup></span></a></li>\n<li><a href="/d/classes/search/cls" class="cls" data-cat="cls"><span class="txt">classes<sup class="c"></sup></span></a></li>\n<li><a href="/d/events/search/eve" class="eve" data-cat="eve"><span class="txt">events<sup class="c"></sup></span></a></li>\n<li><a href="/d/general-community/search/com" class="com" data-cat="com"><span class="txt">general<sup class="c"></sup></span></a></li>\n<li><a href="/d/groups/search/grp" class="grp" data-cat="grp"><span class="txt">groups<sup class="c"></sup></span></a></li>\n<li><a href="/d/local-news-and-views/search/vnn" class="vnn" data-cat="vnn"><span class="txt">local&nbsp;news<sup class="c"></sup></span></a></li>\n</ul>\n<ul id="ccc1" class="mc">\n<li><a href="/d/lost-found/search/laf" class="laf" data-cat="laf"><span class="txt">lost+found<sup class="c"></sup></span></a></li>\n<li><a href="/d/missed-connections/search/mis" class="mis" data-cat="mis"><span class="txt">missed connections<sup class="c"></sup></span></a></li>\n<li><a href="/d/musicians/search/muc" class="muc" data-cat="muc"><span class="txt">musicians<sup class="c"></sup></span></a></li>\n<li><a href="/d/pets/search/pet" class="pet" data-cat="pet"><span class="txt">pets<sup class="c"></sup></span></a></li>\n<li><a href="/d/politics/search/pol" class="pol" data-cat="pol"><span class="txt">politics<sup class="c"></sup></span></a></li>\n<li><a href="/d/rants-raves/search/rnr" class="rnr" data-cat="rnr"><span class="txt">rants &amp; raves<sup class="c"></sup></span></a></li>\n<li><a href="/d/rideshare/search/rid" class="rid" data-cat="rid"><span class="txt">rideshare<sup class="c"></sup></span></a></li>\n<li><a href="/d/volunteers/search/vol" class="vol" data-cat="vol"><span class="txt">volunteers<sup class="c"></sup></span></a></li>\n</ul>\n</div>\n</div>\n\n                \n        <div id="bbb" class="col">\n        <h4 class="ban"><a href="/d/services/search/bbb" class="bbb" data-alltitle="all services" data-cat="bbb"><span class="txt">services<sup class="c"></sup></span></a></h4>\n        <div class="cats">\n        <ul id="bbb0" class="left">\n<li><a href="/d/automotive-services/search/aos" class="aos" data-cat="aos"><span class="txt">automotive<sup class="c"></sup></span></a></li>\n<li><a href="/d/beauty-services/search/bts" class="bts" data-cat="bts"><span class="txt">beauty<sup class="c"></sup></span></a></li>\n<li><a href="/d/cell-phone-mobile-services/search/cms" class="cms" data-cat="cms"><span class="txt">cell/mobile<sup class="c"></sup></span></a></li>\n<li><a href="/d/computer-services/search/cps" class="cps" data-cat="cps"><span class="txt">computer<sup class="c"></sup></span></a></li>\n<li><a href="/d/creative-services/search/crs" class="crs" data-cat="crs"><span class="txt">creative<sup class="c"></sup></span></a></li>\n<li><a href="/d/cycle-services/search/cys" class="cys" data-cat="cys"><span class="txt">cycle<sup class="c"></sup></span></a></li>\n<li><a href="/d/event-services/search/evs" class="evs" data-cat="evs"><span class="txt">event<sup class="c"></sup></span></a></li>\n<li><a href="/d/farm-garden-services/search/fgs" class="fgs" data-cat="fgs"><span class="txt">farm+garden<sup class="c"></sup></span></a></li>\n<li><a href="/d/financial-services/search/fns" class="fns" data-cat="fns"><span class="txt">financial<sup class="c"></sup></span></a></li>\n<li><a href="/d/household-services/search/hss" class="hss" data-cat="hss"><span class="txt">household<sup class="c"></sup></span></a></li>\n</ul>\n<ul id="bbb1" class="mc">\n<li><a href="/d/labor-hauling-moving/search/lbs" class="lbs" data-cat="lbs"><span class="txt">labor/move<sup class="c"></sup></span></a></li>\n<li><a href="/d/legal-services/search/lgs" class="lgs" data-cat="lgs"><span class="txt">legal<sup class="c"></sup></span></a></li>\n<li><a href="/d/lessons-tutoring/search/lss" class="lss" data-cat="lss"><span class="txt">lessons<sup class="c"></sup></span></a></li>\n<li><a href="/d/marine-services/search/mas" class="mas" data-cat="mas"><span class="txt">marine<sup class="c"></sup></span></a></li>\n<li><a href="/d/pet-services/search/pas" class="pas" data-cat="pas"><span class="txt">pet<sup class="c"></sup></span></a></li>\n<li><a href="/d/real-estate-services/search/rts" class="rts" data-cat="rts"><span class="txt">real estate<sup class="c"></sup></span></a></li>\n<li><a href="/d/skilled-trade-services/search/sks" class="sks" data-cat="sks"><span class="txt">skilled trade<sup class="c"></sup></span></a></li>\n<li><a href="/d/small-biz-ads/search/biz" class="biz" data-cat="biz"><span class="txt">sm biz ads<sup class="c"></sup></span></a></li>\n<li><a href="/d/travel-vacation-services/search/trv" class="trv" data-cat="trv"><span class="txt">travel/vac<sup class="c"></sup></span></a></li>\n<li><a href="/d/writing-editing-translation/search/wet" class="wet" data-cat="wet"><span class="txt">write/ed/tran<sup class="c"></sup></span></a></li>\n</ul>\n</div>\n</div>\n\n                \n        <div id="forums" class="col">\n        <h4 class="ban"><a href="https://forums.craigslist.org/?areaID=18" class="forums" data-cat="forums"><span class="txt">discussion forums<sup class="c"></sup></span></a></h4>\n        <div class="cats">\n        <ul id="forums0" class="left">\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=5178"><span class="txt">android<sup class="c"></sup></span></a></li>\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=3232"><span class="txt">apple<sup class="c"></sup></span></a></li>\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=49"><span class="txt">arts<sup class="c"></sup></span></a></li>\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=78"><span class="txt">atheist<sup class="c"></sup></span></a></li>\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=5"><span class="txt">autos<sup class="c"></sup></span></a></li>\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=88"><span class="txt">beauty<sup class="c"></sup></span></a></li>\n<li><a href="https://forums.craigslist.org/?areaID=18&amp;forumID=95"><span class="txt">bikes<sup class="c"></sup></span>

In [6]:
# Turn response into a soup object to parse html content
soup = BeautifulSoup(page.content, 'html.parser')

In [7]:
# Use find method
soup.find('title')

In [8]:
# Use find_all method to find all "a" tags
a = soup.find_all('a')

In [9]:
a
## type(a)

[<a class="appstorebtn" href="https://play.google.com/store/apps/details?id=org.craigslist.CraigslistMobile">
         Android
     </a>,
 <a class="appstorebtn" href="https://apps.apple.com/us/app/craigslist/id1336642410">
         iOS
     </a>,
 <a class="header-logo" href="/" name="logoLink">CL</a>,
 <a href="/">phoenix</a>,
 <a href="https://post.craigslist.org/c/phx">post</a>,
 <a href="https://accounts.craigslist.org/login/home">account</a>,
 <a class="favlink" href="#"><span aria-hidden="true" class="icon icon-star fav"></span><span class="fav-number"></span><span class="fav-label"> favorites</span></a>,
 <a class="to-banish-page-link" href="#">
 <span aria-hidden="true" class="icon icon-trash red"></span>
 <span class="banished_count"></span>
 <span class="discards-label"> hidden</span>
 </a>,
 <a class="header-logo" href="/">CL</a>,
 <a href="/cph/" title="central/south phx">cph</a>,
 <a href="/evl/" title="east valley">evl</a>,
 <a href="/nph/" title="phx north">nph</a>,
 <a href="/wvl/" title="west valley">wvl</a>,
 <a href="https://www.craigslist.org/about/sites">craigslist</a>,
 <a href="https://post.craigslist.org/c/phx" id="post">create a posting</a>,
 <a href="https://accounts.craigslist.org/login/home">my account</a>,
 <a href="/d/events-classes/search/eee">event calendar</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-07">7</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-08">8</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-09">9</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-10">10</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-11">11</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-12">12</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-13">13</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-14">14</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-15">15</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-16">16</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-17">17</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-18">18</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-19">19</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-20">20</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-21">21</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-22">22</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-23">23</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-24">24</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-25">25</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-26">26</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-27">27</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-28">28</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-29">29</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-30">30</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-07-31">31</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-08-01">1</a>,
 <a href="//phoenix.craigslist.org/d/events-classes/search/eee?sale_date=2020-08-02">2</a>,
 <a href="https://www.craigslist.org/about/craigslist_app">craigslist app<sup class="neu">new</sup></a>,
 <a href="https://www.craigslist.org/about/help/">help, faq, abuse, legal</a>,
 <a href="https://www.craigslist.org/about/scams">avoid scams &amp; fraud</a>,
 <a href="https://www.craigslist.org/about/safety">personal safety tips</a>,
 <a href="//www.craigslist.org/about/terms.of.use.en-us">terms of use<sup class="neu">new</sup></a>,
 <a href="https://www.craigslist.org/about/privacy.policy">privacy policy</a>,
 <a href="https://www.craigslist.org/about/help/system-status">system status</a>,
 <a href="https://www.craigslist.org/about/">about craigslist</a>,
 <a href="https://www.craigslist.org/about/open_source">craigslist open source</a>,
 <a href="http://blog.craigslist.org/">craigslist blog</a>,
 <a href="https://www.craigslist.org/about/best/all/">best-of-craigslist</a>,
 <a href="http://www.craigslistjoe.com/">"craigslist joe"</a>,
 <a href="https://craignewmarkphilanthropies.org/">craig newmark<br/>philanthropies</a>,
 <a class="ccc" data-alltitle="all community" data-cat="ccc" href="/d/community/search/ccc"><span class="txt">community<sup class="c"></sup></span></a>,
 <a class="act" data-cat="act" href="/d/activity-partners/search/act"><span class="txt">activities<sup class="c"></sup></span></a>,
 <a class="ats" data-cat="ats" href="/d/artists/search/ats"><span class="txt">artists<sup class="c"></sup></span></a>,
 <a class="kid" data-cat="kid" href="/d/childcare/search/kid"><span class="txt">childcare<sup class="c"></sup></span></a>,
 <a class="cls" data-cat="cls" href="/d/classes/search/cls"><span class="txt">classes<sup class="c"></sup></span></a>,
 <a class="eve" data-cat="eve" href="/d/events/search/eve"><span class="txt">events<sup class="c"></sup></span></a>,
 <a class="com" data-cat="com" href="/d/general-community/search/com"><span class="txt">general<sup class="c"></sup></span></a>,
 <a class="grp" data-cat="grp" href="/d/groups/search/grp"><span class="txt">groups<sup class="c"></sup></span></a>,
 <a class="vnn" data-cat="vnn" href="/d/local-news-and-views/search/vnn"><span class="txt">local news<sup class="c"></sup></span></a>,
 <a class="laf" data-cat="laf" href="/d/lost-found/search/laf"><span class="txt">lost+found<sup class="c"></sup></span></a>,
 <a class="mis" data-cat="mis" href="/d/missed-connections/search/mis"><span class="txt">missed connections<sup class="c"></sup></span></a>,
 <a class="muc" data-cat="muc" href="/d/musicians/search/muc"><span class="txt">musicians<sup class="c"></sup></span></a>,
 <a class="pet" data-cat="pet" href="/d/pets/search/pet"><span class="txt">pets<sup class="c"></sup></span></a>,
 <a class="pol" data-cat="pol" href="/d/politics/search/pol"><span class="txt">politics<sup class="c"></sup></span></a>,
 <a class="rnr" data-cat="rnr" href="/d/rants-raves/search/rnr"><span class="txt">rants &amp; raves<sup class="c"></sup></span></a>,
 <a class="rid" data-cat="rid" href="/d/rideshare/search/rid"><span class="txt">rideshare<sup class="c"></sup></span></a>,
 <a class="vol" data-cat="vol" href="/d/volunteers/search/vol"><span class="txt">volunteers<sup class="c"></sup></span></a>,
 <a class="bbb" data-alltitle="all services" data-cat="bbb" href="/d/services/search/bbb"><span class="txt">services<sup class="c"></sup></span></a>,
 <a class="aos" data-cat="aos" href="/d/automotive-services/search/aos"><span class="txt">automotive<sup class="c"></sup></span></a>,
 <a class="bts" data-cat="bts" href="/d/beauty-services/search/bts"><span class="txt">beauty<sup class="c"></sup></span></a>,
 <a class="cms" data-cat="cms" href="/d/cell-phone-mobile-services/search/cms"><span class="txt">cell/mobile<sup class="c"></sup></span></a>,
 <a class="cps" data-cat="cps" href="/d/computer-services/search/cps"><span class="txt">computer<sup class="c"></sup></span></a>,
 <a class="crs" data-cat="crs" href="/d/creative-services/search/crs"><span class="txt">creative<sup class="c"></sup></span></a>,
 <a class="cys" data-cat="cys" href="/d/cycle-services/search/cys"><span class="txt">cycle<sup class="c"></sup></span></a>,
 <a class="evs" data-cat="evs" href="/d/event-services/search/evs"><span class="txt">event<sup class="c"></sup></span></a>,
 <a class="fgs" data-cat="fgs" href="/d/farm-garden-services/search/fgs"><span class="txt">farm+garden<sup class="c"></sup></span></a>,
 <a class="fns" data-cat="fns" href="/d/financial-services/search/fns"><span class="txt">financial<sup class="c"></sup></span></a>,
 <a class="hss" data-cat="hss" href="/d/household-services/search/hss"><span class="txt">household<sup class="c"></sup></span></a>,
 <a class="lbs" data-cat="lbs" href="/d/labor-hauling-moving/search/lbs"><span class="txt">labor/move<sup class="c"></sup></span></a>,
 <a class="lgs" data-cat="lgs" href="/d/legal-services/search/lgs"><span class="txt">legal<sup class="c"></sup></span></a>,
 <a class="lss" data-cat="lss" href="/d/lessons-tutoring/search/lss"><span class="txt">lessons<sup class="c"></sup></span></a>,
 <a class="mas" data-cat="mas" href="/d/marine-services/search/mas"><span class="txt">marine<sup class="c"></sup></span></a>,
 <a class="pas" data-cat="pas" href="/d/pet-services/search/pas"><span class="txt">pet<sup class="c"></sup></span></a>,
 <a class="rts" data-cat="rts" href="/d/real-estate-services/search/rts"><span class="txt">real estate<sup class="c"></sup></span></a>,
 <a class="sks" data-cat="sks" href="/d/skilled-trade-services/search/sks"><span class="txt">skilled trade<sup class="c"></sup></span></a>,
 <a class="biz" data-cat="biz" href="/d/small-biz-ads/search/biz"><span class="txt">sm biz ads<sup class="c"></sup></span></a>,
 <a class="trv" data-cat="trv" href="/d/travel-vacation-services/search/trv"><span class="txt">travel/vac<sup class="c"></sup></span></a>,
 <a class="wet" data-cat="wet" href="/d/writing-editing-translation/search/wet"><span class="txt">write/ed/tran<sup class="c"></sup></span></a>,
 <a class="forums" data-cat="forums" href="https://forums.craigslist.org/?areaID=18"><span class="txt">discussion forums<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=5178"><span class="txt">android<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=3232"><span class="txt">apple<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=49"><span class="txt">arts<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=78"><span class="txt">atheist<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=5"><span class="txt">autos<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=88"><span class="txt">beauty<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=95"><span class="txt">bikes<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=47"><span class="txt">celebs<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=34"><span class="txt">comp<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=1564"><span class="txt">cosmos<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=122"><span class="txt">diet<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=76"><span class="txt">divorce<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=130"><span class="txt">dying<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=99"><span class="txt">eco<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=8"><span class="txt">feedbk<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=41"><span class="txt">film<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=64"><span class="txt">fixit<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=22"><span class="txt">food<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=2007"><span class="txt">frugal<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=85"><span class="txt">gaming<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=54"><span class="txt">garden<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=575"><span class="txt">haiku<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=9"><span class="txt">help<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=81"><span class="txt">history<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=6"><span class="txt">housing<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=7"><span class="txt">jobs<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=1257"><span class="txt">jokes<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=73"><span class="txt">legal<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=1991"><span class="txt">linux<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=79"><span class="txt">manners<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=1926"><span class="txt">marriage<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=53"><span class="txt">money<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=24"><span class="txt">music<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=4"><span class="txt">open<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=16"><span class="txt">outdoor<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=39"><span class="txt">parent<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=26"><span class="txt">pets<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=71"><span class="txt">philos<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=5500"><span class="txt">photo<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=20"><span class="txt">politics<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=29"><span class="txt">psych<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=12"><span class="txt">recover<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=59"><span class="txt">religion<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=28"><span class="txt">rofo<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=96"><span class="txt">science<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=93"><span class="txt">spirit<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=32"><span class="txt">sports<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=2012"><span class="txt">super<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=1040"><span class="txt">tax<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=42"><span class="txt">travel<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=98"><span class="txt">tv<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=2400"><span class="txt">vegan<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=7000"><span class="txt">words<sup class="c"></sup></span></a>,
 <a href="https://forums.craigslist.org/?areaID=18&amp;forumID=27"><span class="txt">writing<sup class="c"></sup></span></a>,
 <a class="hhh" data-alltitle="all housing" data-cat="hhh" href="/d/housing/search/hhh"><span class="txt">housing<sup class="c"></sup></span></a>,
 <a class="apa" data-cat="apa" href="/d/apts-housing-for-rent/search/apa"><span class="txt">apts / housing<sup class="c"></sup></span></a>,
 <a class="swp" data-cat="swp" href="/d/housing-swap/search/swp"><span class="txt">housing swap<sup class="c"></sup></span></a>,
 <a class="hsw" data-cat="hsw" href="/d/all-housing-wanted/search/hsw"><span class="txt">housing wanted<sup class="c"></sup></span></a>,
 <a class="off" data-cat="off" href="/d/office-commercial/search/off"><span class="txt">office / commercial<sup class="c"></sup></span></a>,
 <a class="prk" data-cat="prk" href="/d/parking-storage/search/prk"><span class="txt">parking / storage<sup class="c"></sup></span></a>,
 <a class="rea" data-cat="rea" href="/d/real-estate/search/rea"><span class="txt">real estate for sale<sup class="c"></sup></span></a>,
 <a class="roo" data-cat="roo" href="/d/rooms-shares/search/roo"><span class="txt">rooms / shared<sup class="c"></sup></span></a>,
 <a class="sha" data-cat="sha" href="/d/wanted%3A-room-share/search/sha"><span class="txt">rooms wanted<sup class="c"></sup></span></a>,
 <a class="sub" data-cat="sub" href="/d/sublets-temporary/search/sub"><span class="txt">sublets / temporary<sup class="c"></sup></span></a>,
 <a class="vac" data-cat="vac" href="/d/vacation-rentals/search/vac"><span class="txt">vacation rentals<sup class="c"></sup></span></a>,
 <a class="sss" data-alltitle="all for sale" data-cat="sss" href="/d/for-sale/search/sss"><span class="txt">for sale<sup class="c"></sup></span></a>,
 <a class="ata" data-cat="ata" href="/d/antiques/search/ata"><span class="txt">antiques<sup class="c"></sup></span></a>,
 <a class="ppa" data-cat="ppa" href="/d/appliances/search/ppa"><span class="txt">appliances<sup class="c"></sup></span></a>,
 <a class="ara" data-cat="ara" href="/d/arts-crafts/search/ara"><span class="txt">arts+crafts<sup class="c"></sup></span></a>,
 <a class="sna" data-cat="sna" href="/d/atvs%2C-utvs%2C-snowmobiles/search/sna"><span class="txt">atv/utv/sno<sup class="c"></sup></span></a>,
 <a class="pta" data-cat="pta" href="/d/auto-parts/search/pta"><span class="txt">auto parts<sup class="c"></sup></span></a>,
 <a class="ava" data-cat="ava" href="/d/aviation/search/ava"><span class="txt">aviation<sup class="c"></sup></span></a>,
 <a class="baa" data-cat="baa" href="/d/baby-kid-stuff/search/baa"><span class="txt">baby+kid<sup class="c"></sup></span></a>,
 <a class="bar" data-cat="bar" href="/d/barter/search/bar"><span class="txt">barter<sup class="c"></sup></span></a>,
 <a class="haa" data-cat="haa" href="/d/health-and-beauty/search/haa"><span class="txt">beauty+hlth<sup class="c"></sup></span></a>,
 <a class="bip" data-cat="bip" href="/d/bicycle-parts/search/bip"><span class="txt">bike parts<sup class="c"></sup></span></a>,
 <a class="bia" data-cat="bia" href="/d/bicycles/search/bia"><span class="txt">bikes<sup class="c"></sup></span></a>,
 <a class="bpa" data-cat="bpa" href="/d/boat-parts-accessories/search/bpa"><span class="txt">boat parts<sup class="c"></sup></span></a>,
 <a class="boo" data-cat="boo" href="/d/boats/search/boo"><span class="txt">boats<sup class="c"></sup></span></a>,

In [10]:
# How to get Tag withint a tag
a[4]
#a[4].span

In [11]:
# Use find method with specified attributes
#soup.find('div')
soup.find('div', attrs={'class': 'jobs'})

<div class="jobs">
<div class="col" id="jjj">
<h4 class="ban"><a class="jjj" data-alltitle="all jobs" data-cat="jjj" href="/d/jobs/search/jjj"><span class="txt">jobs<sup class="c"></sup></span></a></h4>
<div class="cats">
<ul id="jjj0">
<li><a class="acc" data-cat="acc" href="/d/accounting-finance/search/acc"><span class="txt">accounting+finance<sup class="c"></sup></span></a></li>
<li><a class="ofc" data-cat="ofc" href="/d/admin-office/search/ofc"><span class="txt">admin / office<sup class="c"></sup></span></a></li>
<li><a class="egr" data-cat="egr" href="/d/architect-engineer-cad/search/egr"><span class="txt">arch / engineering<sup class="c"></sup></span></a></li>
<li><a class="med" data-cat="med" href="/d/art-media-design/search/med"><span class="txt">art / media / design<sup class="c"></sup></span></a></li>
<li><a class="sci" data-cat="sci" href="/d/science-biotech/search/sci"><span class="txt">biotech / science<sup class="c"></sup></span></a></li>
<li><a class="bus" data-cat="bus" href="/d/business-mgmt/search/bus"><span class="txt">business / mgmt<sup class="c"></sup></span></a></li>
<li><a class="csr" data-cat="csr" href="/d/customer-service/search/csr"><span class="txt">customer service<sup class="c"></sup></span></a></li>
<li><a class="edu" data-cat="edu" href="/d/education-teaching/search/edu"><span class="txt">education<sup class="c"></sup></span></a></li>
<li><a class="etc" data-cat="etc" href="/d/et-cetera/search/etc"><span class="txt">etc / misc<sup class="c"></sup></span></a></li>
<li><a class="fbh" data-cat="fbh" href="/d/food-beverage-hospitality/search/fbh"><span class="txt">food / bev / hosp<sup class="c"></sup></span></a></li>
<li><a class="lab" data-cat="lab" href="/d/general-labor/search/lab"><span class="txt">general labor<sup class="c"></sup></span></a></li>
<li><a class="gov" data-cat="gov" href="/d/government/search/gov"><span class="txt">government<sup class="c"></sup></span></a></li>
<li><a class="hum" data-cat="hum" href="/d/human-resource/search/hum"><span class="txt">human resources<sup class="c"></sup></span></a></li>
<li><a class="lgl" data-cat="lgl" href="/d/legal-paralegal/search/lgl"><span class="txt">legal  /  paralegal<sup class="c"></sup></span></a></li>
<li><a class="mnu" data-cat="mnu" href="/d/manufacturing/search/mnu"><span class="txt">manufacturing<sup class="c"></sup></span></a></li>
<li><a class="mar" data-cat="mar" href="/d/marketing-advertising-pr/search/mar"><span class="txt">marketing / pr / ad<sup class="c"></sup></span></a></li>
<li><a class="hea" data-cat="hea" href="/d/healthcare/search/hea"><span class="txt">medical / health<sup class="c"></sup></span></a></li>
<li><a class="npo" data-cat="npo" href="/d/nonprofit/search/npo"><span class="txt">nonprofit sector<sup class="c"></sup></span></a></li>
<li><a class="rej" data-cat="rej" href="/d/real-estate/search/rej"><span class="txt">real estate<sup class="c"></sup></span></a></li>
<li><a class="ret" data-cat="ret" href="/d/retail-wholesale/search/ret"><span class="txt">retail / wholesale<sup class="c"></sup></span></a></li>
<li><a class="sls" data-cat="sls" href="/d/sales/search/sls"><span class="txt">sales / biz dev<sup class="c"></sup></span></a></li>
<li><a class="spa" data-cat="spa" href="/d/salon-spa-fitness/search/spa"><span class="txt">salon / spa / fitness<sup class="c"></sup></span></a></li>
<li><a class="sec" data-cat="sec" href="/d/security/search/sec"><span class="txt">security<sup class="c"></sup></span></a></li>
<li><a class="trd" data-cat="trd" href="/d/skilled-trades-artisan/search/trd"><span class="txt">skilled trade / craft<sup class="c"></sup></span></a></li>
<li><a class="sof" data-cat="sof" href="/d/software-qa-dba-etc/search/sof"><span class="txt">software / qa / dba<sup class="c"></sup></span></a></li>
<li><a class="sad" data-cat="sad" href="/d/systems-networking/search/sad"><span class="txt">systems / network<sup class="c"></sup></span></a></li>
<li><a class="tch" data-cat="tch" href="/d/technical-support/search/tch"><span class="txt">technical support<sup class="c"></sup></span></a></li>
<li><a class="trp" data-cat="trp" href="/d/transportation/search/trp"><span class="txt">transport<sup class="c"></sup></span></a></li>
<li><a class="tfr" data-cat="tfr" href="/d/tv-film-video-radio/search/tfr"><span class="txt">tv / film / video<sup class="c"></sup></span></a></li>
<li><a class="web" data-cat="web" href="/d/web-html-info-design/search/web"><span class="txt">web / info design<sup class="c"></sup></span></a></li>
<li><a class="wri" data-cat="wri" href="/d/writing-editing/search/wri"><span class="txt">writing / editing<sup class="c"></sup></span></a></li>
</ul>
</div>
</div>
<div class="col" id="ggg">
<h4 class="ban"><a class="ggg" data-alltitle="all gigs" data-cat="ggg" href="/d/gigs/search/ggg"><span class="txt">gigs<sup class="c"></sup></span></a></h4>
<div class="cats">
<ul class="left" id="ggg0">
<li><a class="cpg" data-cat="cpg" href="/d/computer-gigs/search/cpg"><span class="txt">computer<sup class="c"></sup></span></a></li>
<li><a class="crg" data-cat="crg" href="/d/creative-gigs/search/crg"><span class="txt">creative<sup class="c"></sup></span></a></li>
<li><a class="cwg" data-cat="cwg" href="/d/crew-gigs/search/cwg"><span class="txt">crew<sup class="c"></sup></span></a></li>
<li><a class="dmg" data-cat="dmg" href="/d/domestic-gigs/search/dmg"><span class="txt">domestic<sup class="c"></sup></span></a></li>
</ul>
<ul class="mc" id="ggg1">
<li><a class="evg" data-cat="evg" href="/d/event-gigs/search/evg"><span class="txt">event<sup class="c"></sup></span></a></li>
<li><a class="lbg" data-cat="lbg" href="/d/labor-gigs/search/lbg"><span class="txt">labor<sup class="c"></sup></span></a></li>
<li><a class="tlg" data-cat="tlg" href="/d/talent-gigs/search/tlg"><span class="txt">talent<sup class="c"></sup></span></a></li>
<li><a class="wrg" data-cat="wrg" href="/d/writing-gigs/search/wrg"><span class="txt">writing<sup class="c"></sup></span></a></li>
</ul>
</div>
</div>
<div class="col" id="rrr">
<h4 class="ban"><a class="rrr" data-alltitle="all resumes" data-cat="rrr" href="/d/resumes/search/rrr"><span class="txt">resumes<sup class="c"></sup></span></a></h4>
<div class="cats">
</div>
</div>
</div>

In [12]:
# Use find method with specified attributes
nearby_cl = soup.find('ul', attrs={'class': 'acitem'})
nearby_cl

<ul class="acitem">
<li class="s"><a href="//albuquerque.craigslist.org/">albuquerque</a>
<li class="s"><a href="//bakersfield.craigslist.org/">bakersfield</a>
<li class="s"><a href="//elpaso.craigslist.org/">el paso</a>
<li class="s"><a href="//farmington.craigslist.org/">farmington</a>
<li class="s"><a href="//flagstaff.craigslist.org/">flagstaff</a>
<li class="s"><a href="//fresno.craigslist.org/">fresno</a>
<li class="s"><a href="//hanford.craigslist.org/">hanford</a>
<li class="s"><a href="//imperial.craigslist.org/">imperial co</a>
<li class="s"><a href="//inlandempire.craigslist.org/">inland empire</a>
<li class="s"><a href="//lascruces.craigslist.org/">las cruces</a>
<li class="s"><a href="//lasvegas.craigslist.org/">las vegas</a>
<li class="s"><a href="//losangeles.craigslist.org/">los angeles</a>
<li class="s"><a href="//mohave.craigslist.org/">mohave co</a>
<li class="s"><a href="//orangecounty.craigslist.org/">orange co</a>
<li class="s"><a href="//palmsprings.craigslist.org/">palm springs</a>
<li class="s"><a href="//prescott.craigslist.org/">prescott</a>
<li class="s"><a href="//provo.craigslist.org/">provo</a>
<li class="s"><a href="//roswell.craigslist.org/">roswell</a>
<li class="s"><a href="//sandiego.craigslist.org/">san diego</a>
<li class="s"><a href="//santabarbara.craigslist.org/">santa barbara</a>
<li class="s"><a href="//santafe.craigslist.org/">santa fe</a>
<li class="s"><a href="//santamaria.craigslist.org/">santa maria</a>
<li class="s"><a href="//showlow.craigslist.org/">show low</a>
<li class="s"><a href="//sierravista.craigslist.org/">sierra vista</a>
<li class="s"><a href="//stgeorge.craigslist.org/">st george</a>
<li class="s"><a href="//tucson.craigslist.org/">tucson</a>
<li class="s"><a href="//ventura.craigslist.org/">ventura</a>
<li class="s"><a href="//visalia.craigslist.org/">visalia-tulare</a>
<li class="s"><a href="//westslope.craigslist.org/">western slope</a>
<li class="s"><a href="//yuma.craigslist.org/">yuma</a>
</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul>

In [13]:
nearby_list = nearby_cl.find_all('a')

In [14]:
nearby_list

[<a href="//albuquerque.craigslist.org/">albuquerque</a>,
 <a href="//bakersfield.craigslist.org/">bakersfield</a>,
 <a href="//elpaso.craigslist.org/">el paso</a>,
 <a href="//farmington.craigslist.org/">farmington</a>,
 <a href="//flagstaff.craigslist.org/">flagstaff</a>,
 <a href="//fresno.craigslist.org/">fresno</a>,
 <a href="//hanford.craigslist.org/">hanford</a>,
 <a href="//imperial.craigslist.org/">imperial co</a>,
 <a href="//inlandempire.craigslist.org/">inland empire</a>,
 <a href="//lascruces.craigslist.org/">las cruces</a>,
 <a href="//lasvegas.craigslist.org/">las vegas</a>,
 <a href="//losangeles.craigslist.org/">los angeles</a>,
 <a href="//mohave.craigslist.org/">mohave co</a>,
 <a href="//orangecounty.craigslist.org/">orange co</a>,
 <a href="//palmsprings.craigslist.org/">palm springs</a>,
 <a href="//prescott.craigslist.org/">prescott</a>,
 <a href="//provo.craigslist.org/">provo</a>,
 <a href="//roswell.craigslist.org/">roswell</a>,
 <a href="//sandiego.craigslist.org/">san diego</a>,
 <a href="//santabarbara.craigslist.org/">santa barbara</a>,
 <a href="//santafe.craigslist.org/">santa fe</a>,
 <a href="//santamaria.craigslist.org/">santa maria</a>,
 <a href="//showlow.craigslist.org/">show low</a>,
 <a href="//sierravista.craigslist.org/">sierra vista</a>,
 <a href="//stgeorge.craigslist.org/">st george</a>,
 <a href="//tucson.craigslist.org/">tucson</a>,
 <a href="//ventura.craigslist.org/">ventura</a>,
 <a href="//visalia.craigslist.org/">visalia-tulare</a>,
 <a href="//westslope.craigslist.org/">western slope</a>,
 <a href="//yuma.craigslist.org/">yuma</a>]

In [15]:
# Create a list of the nearby city names
names_list = []
for i in range(len(nearby_list)):
    names_list.append(nearby_list[i].get_text())

In [16]:
names_list

['albuquerque',
 'bakersfield',
 'el paso',
 'farmington',
 'flagstaff',
 'fresno',
 'hanford',
 'imperial co',
 'inland empire',
 'las cruces',
 'las vegas',
 'los angeles',
 'mohave co',
 'orange co',
 'palm springs',
 'prescott',
 'provo',
 'roswell',
 'san diego',
 'santa barbara',
 'santa fe',
 'santa maria',
 'show low',
 'sierra vista',
 'st george',
 'tucson',
 'ventura',
 'visalia-tulare',
 'western slope',
 'yuma']

In [17]:
# Create a list of the nearby citities links
link_list = []
for i in range(len(nearby_list)):
    link_list.append(nearby_list[i].get('href'))

In [18]:
link_list

['//albuquerque.craigslist.org/',
 '//bakersfield.craigslist.org/',
 '//elpaso.craigslist.org/',
 '//farmington.craigslist.org/',
 '//flagstaff.craigslist.org/',
 '//fresno.craigslist.org/',
 '//hanford.craigslist.org/',
 '//imperial.craigslist.org/',
 '//inlandempire.craigslist.org/',
 '//lascruces.craigslist.org/',
 '//lasvegas.craigslist.org/',
 '//losangeles.craigslist.org/',
 '//mohave.craigslist.org/',
 '//orangecounty.craigslist.org/',
 '//palmsprings.craigslist.org/',
 '//prescott.craigslist.org/',
 '//provo.craigslist.org/',
 '//roswell.craigslist.org/',
 '//sandiego.craigslist.org/',
 '//santabarbara.craigslist.org/',
 '//santafe.craigslist.org/',
 '//santamaria.craigslist.org/',
 '//showlow.craigslist.org/',
 '//sierravista.craigslist.org/',
 '//stgeorge.craigslist.org/',
 '//tucson.craigslist.org/',
 '//ventura.craigslist.org/',
 '//visalia.craigslist.org/',
 '//westslope.craigslist.org/',
 '//yuma.craigslist.org/']

In [19]:
# Create pandas dataframe with specified column name
columnHeaders = ['Nearby', 'Links']
df = pd.DataFrame(columns = columnHeaders)
df

Empty DataFrame
Columns: [Nearby, Links]
Index: []

In [20]:
# Append lists to dataframe
for i in range(len(nearby_list)):
    df = df.append({'Nearby': names_list[i], 'Links': link_list[i]}, ignore_index = True)

In [21]:
df

            Nearby                           Links
0      albuquerque   //albuquerque.craigslist.org/
1      bakersfield   //bakersfield.craigslist.org/
2          el paso        //elpaso.craigslist.org/
3       farmington    //farmington.craigslist.org/
4        flagstaff     //flagstaff.craigslist.org/
5           fresno        //fresno.craigslist.org/
6          hanford       //hanford.craigslist.org/
7      imperial co      //imperial.craigslist.org/
8    inland empire  //inlandempire.craigslist.org/
9       las cruces     //lascruces.craigslist.org/
10       las vegas      //lasvegas.craigslist.org/
11     los angeles    //losangeles.craigslist.org/
12       mohave co        //mohave.craigslist.org/
13       orange co  //orangecounty.craigslist.org/
14    palm springs   //palmsprings.craigslist.org/
15        prescott      //prescott.craigslist.org/
16           provo         //provo.craigslist.org/
17         roswell       //roswell.craigslist.org/
18       san diego      //sandiego.craigslist.org/
19   santa barbara  //santabarbara.craigslist.org/
20        santa fe       //santafe.craigslist.org/
21     santa maria    //santamaria.craigslist.org/
22        show low       //showlow.craigslist.org/
23    sierra vista   //sierravista.craigslist.org/
24       st george      //stgeorge.craigslist.org/
25          tucson        //tucson.craigslist.org/
26         ventura       //ventura.craigslist.org/
27  visalia-tulare       //visalia.craigslist.org/
28   western slope     //westslope.craigslist.org/
29            yuma          //yuma.craigslist.org/

In [22]:
for i in link_list:
    url = "https:" + i
    page = requests.get(url)
    # Do whatever you need and traverse through links